# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-OkiLab-ExtractPlace
version:      0.02
version_from: lib/WebService/OkiLab/ExtractPlace.pm
installdirs:  site
requires:
    Class::ErrorHandler:           0
    JSON:                          0
    LWP::UserAgent:                0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
